language: go
go:
  - 1.1
  - 1.2
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
script:
  - go build -v ./...
  - go test -v ./...
  - $HOME/gopath/bin/goveralls HKd1xqMsHvFxNA7LjuK6iZFYlBQoyFTxw
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
